export class ReviewEntity {
  constructor(
    public readonly id: string,
    public readonly user: string,
    public readonly provider: string,
    public readonly rating: number,
    public readonly order?: string,
    public readonly booking?: string,
    public readonly comment?: string,
    public readonly serviceQuality?: number,
    public readonly punctuality?: number,
    public readonly professionalism?: number,
    public readonly valueForMoney?: number,
    public readonly images: string[] = [],
    public readonly providerResponse?: string,
    public readonly providerRespondedAt?: Date,
    public readonly isVisible: boolean = true,
    public readonly isFlagged: boolean = false,
    public readonly flagReason?: string,
    public readonly helpfulCount: number = 0,
    public readonly helpfulVoters: string[] = [],
    public readonly createdAt?: Date,
    public readonly updatedAt?: Date,
  ) {
    this.validate();
  }

  private validate() {
    if (!this.user) throw new Error('User is required');
    if (!this.provider) throw new Error('Provider is required');
    if (this.rating < 1 || this.rating > 5) {
      throw new Error('Rating must be between 1 and 5');
    }
    if (!this.order && !this.booking) {
      throw new Error('Review must be linked to an order or a booking');
    }
  }

  static create(props: {
    user: string;
    provider: string;
    rating: number;
    order?: string;
    booking?: string;
    comment?: string;
    serviceQuality?: number;
    punctuality?: number;
    professionalism?: number;
    valueForMoney?: number;
    images?: string[];
  }): ReviewEntity {
    return new ReviewEntity(
      '', // ID will be generated by DB
      props.user,
      props.provider,
      props.rating,
      props.order,
      props.booking,
      props.comment,
      props.serviceQuality,
      props.punctuality,
      props.professionalism,
      props.valueForMoney,
      props.images || [],
    );
  }
}
