export const PERMISSIONS_KEY = 'permissions';

export const ADMIN_PERMISSIONS = [
  '*',
  'admin.profile',
  'admins.read',
  'admins.create',
  'admins.update',
  'admins.delete',
  'analytics.read',
  'audit.read',
  'finance.read',
  'finance.update',
  'notifications.read',
  'notifications.create',
  'orders.read',
  'orders.update',
  'orders.cancel',
  'orders.delete',
  'bookings.read',
  'bookings.update',
  'bookings.cancel',
  'providers.read',
  'providers.approve',
  'providers.reject',
  'providers.update',
  'reviews.read',
  'reviews.update',
  'reviews.delete',
  'services.read',
  'services.create',
  'services.update',
  'services.delete',
  'subscriptions.read',
  'subscriptions.create',
  'subscriptions.update',
  'subscriptions.delete',
  'settings.read',
  'settings.update',
  'users.read',
  'users.update',
  'users.delete',
  'users.status',
] as const;
